package com.liteldev.headeroutput.generate

import com.liteldev.headeroutput.HeaderOutput
import java.io.File

object NamespaceGenerator {

    fun generate() {
        HeaderOutput.namespaceMap.forEach { (name, namespaceType) ->
            val file = File(HeaderOutput.GENERATE_PATH, namespaceType.getPath())
            file.writeText(
                """
/**
 * @file  $name.hpp
 * @note  This Header is auto generated by LiteLoaderBDS Toolchain.
 *
 */
#pragma once
#define AUTO_GENERATED
#include "${namespaceType.getGlobalRelativePath()}"
${namespaceType.getRelativeInclusions()}
#define BEFORE_EXTRA
${namespaceType.beforeExtra}
#undef BEFORE_EXTRA

${run { namespaceType.comment.ifEmpty { "/**\n * @brief MC namespace $name.\n *\n */" } }}
namespace $name {

#define AFTER_EXTRA
${namespaceType.afterExtra}
#undef AFTER_EXTRA
${namespaceType.genPublic()}
};
""".trimIndent()
            )
        }
    }
}