[config]
rootPath = "mc"
enableRelativePath = false

[replacement]

regex = [
    { regex = "unsigned __int64", to = "uint64_t" },
    { regex = "__int64", to = "int64_t" },
    { regex = "(?:enum\\sclass|class|struct)\\s*std::", to = "std::" },
    { regex = "std::chrono::duration<int64_t, ?std::ratio<1, ?1000000000> ?>", to = "std::chrono::nanoseconds" },
    { regex = "std::chrono::duration<int64_t, ?std::ratio<1, ?1000000> ?>", to = "std::chrono::microseconds" },
    { regex = "std::chrono::duration<int64_t, ?std::ratio<1, ?1000> ?>", to = "std::chrono::milliseconds" },
    { regex = "std::chrono::duration<int64_t, ?std::ratio<1, ?1> ?>", to = "std::chrono::seconds" },
    { regex = "std::chrono::duration<int, ?std::ratio<60, ?1> ?>", to = "std::chrono::minutes" },
    { regex = "std::chrono::time_point<std::chrono::steady_clock, ?std::chrono::nanoseconds>", to = "std::chrono::time_point<std::chrono::steady_clock>" },
    { regex = "std::basic_string<char, ?std::char_traits<char>, ?std::allocator<char ?> ?>", to = "std::string" },
    { regex = "std::basic_string_view<char, ?std::char_traits<char ?> ?>", to = "std::string_view" },
    { regex = "std::(\\w*)<(.*),\\s*std::default_delete<\\s*\\2\\s*>\\s*>", to = "std::$1<$2>" },
    { regex = "std::map<(.*),\\s*(.*),\\s*std::less<\\s*\\1\\s*>,\\s*std::allocator<\\s*std::pair<\\s*\\1\\s*const\\s*,\\s*\\2\\s*>\\s*>\\s*>", to = "std::map<$1,$2>" },
    { regex = "std::unordered_map<(.*),\\s*(.*),\\s*std::hash<\\s*\\1\\s*>,\\s*std::equal_to<\\s*\\1\\s*>,\\s*std::allocator<\\s*std::pair<\\s*\\1\\s*const\\s*,\\s*\\2\\s*>\\s*>\\s*>", to = "std::unordered_map<$1,$2>" },
    { regex = "std::map<(.*),\\s*(.*),\\s*std::less<\\s*\\1\\s*>,\\s*std::allocator<\\s*std::pair<\\s*\\1\\s*const\\s*,\\s*\\2\\s*>\\s*>\\s*>", to = "std::map<$1,$2>" },
    { regex = "std::unordered_map<(.*),\\s*(.*),\\s*std::hash<\\s*\\1\\s*>,\\s*std::equal_to<\\s*\\1\\s*>,\\s*std::allocator<\\s*std::pair<\\s*\\1\\s*const\\s*,\\s*\\2\\s*>\\s*>\\s*>", to = "std::unordered_map<$1,$2>" },
    { regex = "std::set<(.*),\\s*std::less<\\s*\\1\\s*>,\\s*std::allocator<\\s*\\1\\s*>\\s*>", to = "std::set<$1>" },
    { regex = "std::unordered_set<(.*),\\s*std::hash<\\s*\\1\\s*>,\\s*std::equal_to<\\s*\\1\\s*>,\\s*std::allocator<\\s*\\1\\s*>\\s*>", to = "std::unordered_set<$1>" },
    { regex = "std::set<(.*),\\s*std::less<\\s*\\1\\s*>,\\s*std::allocator<\\s*\\1\\s*>\\s*>", to = "std::set<$1>" },
    { regex = "std::unordered_set<(.*),\\s*std::hash<\\s*\\1\\s*>,\\s*std::equal_to<\\s*\\1\\s*>,\\s*std::allocator<\\s*\\1\\s*>\\s*>", to = "std::unordered_set<$1>" },
    { regex = "std::(\\w*)<(.*),\\s*std::allocator<\\s*\\2\\s*>\\s*>", to = "std::$1<$2>" },
    { regex = "class gsl::span<(.*),\\s*-1>", to = "class gsl::span<$1>" },
    { regex = "class gsl::span<(.*),\\s*-1>", to = "class gsl::span<$1>" },
]

[exclusion]

regex = [
    "^$",
    "^struct .*$",
    "^unity_.*$", # preview
    "^class .*$",
    ".*(@|\\s|<).*",
    "^(?:std|gsl|entt|rapidjson|type_info|leveldb|asio|websocketpp|fmt).*",
    "^Concurrency(?:::.*)*$", # microsft Concurrency, no usage. pplinterface.h
    "_WSABUF", # ws2def.h
    "addrinfo", # ws2def.h
    "sockaddr", # ws2def.h
    "sockaddr_in", # ws2def.h
    "sockaddr_in6", # ws2ipdef.h
    "tm", # corecrt_wtime.h
    "_Mbstatet", # corecrt.h
    "HWND__", # DirectX
    "_WINHTTP_WEB_SOCKET_BUFFER_TYPE", # winhttp.h
    "__std_win_error", # xfilesystem_abi.h
    "wspp_websocket_impl",
]

[sort]
parent = [
    #    { parent = "Actor", dst = "Actor" },
    #    { parent = "ActorBlock", dst = "ActorBlock" },
    #    { parent = "BehaviorDefinition", dst = "BehaviorDefinition" },
    #    { parent = "Block", dst = "Block" },
    #    { parent = "BlockActor", dst = "BlockActor" },
    #    { parent = "BlockLegacy", dst = "BlockLegacy" },
    #    { parent = "Item", dst = "Item" },
    #    { parent = "Packet", dst = "Packet" },
    #    { parent = "Command", dst = "Command" }
]

regex = [
    { regex = ".*RakNet.*", dst = "deps/raknet", override = false },
    { regex = "^Has.*Filter$", dst = "world/actor/selectors", override = false },
    { regex = "^CameraPresetsInternals::.*", dst = "world/actor/common", override = false },
    { regex = "^Crypto::Hash::.*", dst = "deps/crypto/hash", override = false },
    { regex = "^Crypto::Random::.*", dst = "deps/crypto/random", override = false },
    { regex = "^Crypto::Symmetric::.*", dst = "deps/crypto/symmetric", override = false },
    { regex = "^Crypto::Asymmetric::.*", dst = "deps/crypto/asymmetric", override = false },
    { regex = "^Crypto::.*", dst = "deps/crypto", override = false },
    { regex = "^AgentCommands::.*", dst = "world/actor/agent", override = true },
    { regex = ".*Packet$", dst = "network/packet", override = false },
    { regex = "^mce::.*", dst = "deps/core/mce", override = false },
    { regex = "^ScriptModuleMinecraftServerUI.*", dst = "scripting/modules/minecraft_ui", override = false },
    { regex = "^ScriptModuleMinecraftServerAdmin.*", dst = "scripting/modules/minecraft_server_admin", override = false },
    { regex = "^ScriptModuleMinecraftNet.*", dst = "scripting/modules/minecraft_net", override = false },
    { regex = "^ScriptModuleMinecraft.*", dst = "scripting/modules/minecraft", override = false },
    { regex = "^Script.*GameTest.*", dst = "external/scripting/gametest", override = false },
    { regex = "^Script.*", dst = "external/scripting", override = false },
    { regex = "^[Ii]mgui.*", dst = "external/imgui", override = false },
    { regex = "^Core::.*", dst = "deps/core", override = false },
    { regex = "^Util::CodeBuilder.*", dst = "codebuilder/utils", override = false },
    { regex = "^CodeBuilder.*", dst = "codebuilder", override = false },
    { regex = "^Bedrock::PubSub::.*", dst = "deps/core/common/bedrock/pubsub", override = false },
    { regex = "^Bedrock::.*", dst = "deps/core/common/bedrock", override = false },
    { regex = "^BedrockLog::.*", dst = "deps/core/common/debug", override = false },
    { regex = "^BedrockBlock.*", dst = "world/level/block/utils", override = false },
    { regex = ".*VanillaBlock.*", dst = "world/level/block/utils", override = false },
    { regex = ".*ComplexAlias.*", dst = "world/level/block/utils", override = false },
    { regex = ".*Json.*", dst = "deps/json", override = false },
    { regex = ".*Component$", dst = "world/components", override = false },
    { regex = ".*BlockActor$", dst = "world/level/block/actor", override = false },
    { regex = "^(?!.*::).*Block$", dst = "world/level/block", override = false },
    { regex = "^Block.*", dst = "world/level/block/utils", override = false },
    { regex = "^[Gg]ame[Tt]est.*", dst = "gametest/framework", override = false },
    { regex = ".*Event$", dst = "events", override = false },
    { regex = ".*Command$", dst = "server/commands", override = false },
    { regex = ".*websocket.*", dst = "websockets", override = false },
    { regex = "^Social::.*", dst = "client/social", override = false },
    { regex = "^persona.*", dst = "client/services/persona", override = false },
    { regex = "^PlayerCapabilities.*", dst = "config", override = false },
    { regex = ".*Container.*", dst = "world/containers", override = false },
    { regex = ".*[Nn]pc.*", dst = "world/actor/npc", override = false },
    { regex = ".*Flag$", dst = "entity/flags", override = false },
    { regex = ".*Test$", dst = "world/filters", override = false },
    { regex = ".*System.*", dst = "world/systems", override = false },
    { regex = "^Util::.*", dst = "deps/core/utility", override = false },
    { regex = "^Actor.*", dst = "entity/utilities", override = false },
    { regex = ".*Utility$", dst = "deps/core/utility", override = false },
    { regex = "^Level.*", dst = "world/level", override = false },
    { regex = "^Network.*", dst = "network", override = false },
    { regex = "^Editor::Cursor::.*", dst = "server/editor/cursor", override = false },
    { regex = "^Editor::.*UI.*", dst = "server/editor/ui", override = false },
    { regex = "^Editor::.*Server.*", dst = "server/editor/server", override = false },
    { regex = "^Editor::.*", dst = "server/editor", override = false },
    { regex = ".*Command.*", dst = "server/commands", override = false },
    { regex = "^Automation.*", dst = "network", override = false },
    { regex = "^[Cc]ereal::internal.*", dst = "deps/cereal/internal", override = false },
    { regex = "^[Cc]ereal.*", dst = "deps/cereal", override = false },
    { regex = "^AgentComponents::Actions::.*", dst = "entity/components/agent/actions", override = false },
    { regex = "^AgentComponents.*", dst = "entity/components/agent", override = false },
    { regex = "^VanillaSurfaceBuilders.*", dst = "world/level/biome/surface", override = false },
    { regex = "^xbox.*", dst = "client/network", override = false },
    { regex = "^BiomeSourceUtil.*", dst = "world/level/biome", override = false },
    { regex = "^ClimateUtils.*", dst = "world/level/biome", override = false },
    { regex = "^ColumnUtils.*", dst = "world/level/levelgen/feature/helpers", override = false },
    { regex = "^CanyonFeatureUtils.*", dst = "world/level/levelgen/feature", override = false },
    { regex = "^CaveFeatureUtils.*", dst = "world/level/levelgen/feature", override = false },
    { regex = "^BlendingDataFactoryUtil.*", dst = "world/level/storage", override = false },
    { regex = "^Puv.*", dst = "deps/puv", override = false },
    { regex = "^snappy.*", dst = "deps/snappy", override = false },
    { regex = "^VolumeInstanceData.*", dst = "volume", override = false },
    { regex = "^VanillaStates.*", dst = "world/level/block/utils", override = false },
    { regex = "^TreeHelper.*", dst = "world/level/levelgen/feature/helpers", override = false },
    { regex = "^SplitBlockUtils.*", dst = "world/level/block/utils", override = false },
    { regex = ".*BlockState.*", dst = "world/level/block/utils", override = false },
    { regex = "^Sculk.*", dst = "world/level/block/utils", override = false },
    { regex = "^PackCapabilities.*", dst = "resources", override = false },
    { regex = "^Resource.*", dst = "resources", override = false },
    { regex = "^GameLightingChecker.*", dst = "world/level/chunk", override = false },
    { regex = "^ExpressionNodeSerializer.*", dst = "util", override = false },
    { regex = "^DripstoneUtils.*", dst = "world/level/levelgen/feature/helpers", override = false },
    { regex = "^DebugUtils.*", dst = "deps/core/common/debug", override = false },
    { regex = "^Concurrency.*", dst = "deps", override = false },
    { regex = "^Common.*", dst = "common", override = false },
    { regex = "^HC.*", dst = "network", override = false },
    { regex = "^http.*", dst = "network", override = false },
    { regex = "^Web.*", dst = "network", override = false },
    { regex = "^I[A-Z].*", dst = "common", override = false },
    { regex = "^Item.*", dst = "world/item/components", override = false },
    { regex = "^Legacy.*", dst = "deps/core/resource", override = false },
    { regex = ".*span.*", dst = "deps/core/utility", override = false },
    { regex = "^Entity.*", dst = "entity", override = false },
    { regex = "^Service.*", dst = "services", override = false },
    { regex = ".*Net.*", dst = "network", override = false },
    { regex = ".*_TP_.*", dst = "network", override = false },
    { regex = ".*Async.*", dst = "network", override = false },
    { regex = ".*Event.*", dst = "world/events", override = false },
    { regex = ".*[Oo]ptional.*", dst = "common/wrapper", override = false },
    { regex = ".*Ptr.*", dst = "common/wrapper", override = false },
    { regex = ".*_ptr$", dst = "common/wrapper", override = false },
    { regex = ".*Ref.*", dst = "common/wrapper", override = false },
    { regex = ".*Result.*", dst = "common/wrapper", override = false },
    { regex = ".*Trim.*", dst = "world/trim", override = false },
    { regex = ".*Achievement.*", dst = "client/achievements", override = false },
    { regex = ".*Biome.*", dst = "world/level/biome", override = false },
    { regex = ".*Chunk.*", dst = "world/level/chunk", override = false },
    { regex = ".*External.*", dst = "world/level", override = false },
    { regex = ".*Player.*", dst = "world/actor/player", override = false },
    { regex = "^VanillaActor.*", dst = "world/actor", override = false },
    { regex = ".*GameMode.*", dst = "world/gamemode", override = false },
    { regex = "^Pack.*", dst = "resources", override = false },
    { regex = "^StructurePool.*", dst = "world/level/levelgen/structure/structurepools", override = false },
    { regex = ".*Structure.*", dst = "world/level/levelgen/structure", override = false },
    { regex = ".*Dimension.*", dst = "world/level/dimension", override = false },
    { regex = ".*GameVersion.*", dst = "resources", override = false },
    { regex = ".*Goal.*", dst = "world/actor/ai/goal", override = false },
    { regex = ".*Block.*", dst = "world/level/block/utils", override = false },
    { regex = ".*Util.*", dst = "util", override = false },
    { regex = "^ComponentIte.*", dst = "world/item/components", override = false },
    { regex = ".*Actor.*", dst = "world/actor/components", override = false },
    { regex = ".*Generator.*", dst = "world/level/levelgen", override = false },
    { regex = ".*Tree.*", dst = "world/level/levelgen/feature/helpers", override = false },
    { regex = "^JS[A-Z].*", dst = "external/scripting", override = false },
    { regex = "^rapidjson.*", dst = "external/rapidjson", override = false },
    { regex = "^glm.*", dst = "external/glm", override = false },
    { regex = "^MicroProfile.*", dst = "external/microprofile", override = false },
    { regex = "^moodycamel.*", dst = "external/concurrentqueue", override = false },
    { regex = "^Im[A-Z].*", dst = "external/imgui", override = false },
    { regex = "^OS::.*", dst = "external/lib_http_client", override = false },
    { regex = "^cg::.*", dst = "deps/CoreGraphics/common", override = false },
    { regex = "^SFAT::.*", dst = "external/sfat", override = false },
    { regex = "^nonstd::.*", dst = "external/nonstd", override = false },
    { regex = "^qrcodegen::.*", dst = "external/qrcodegen", override = false },
    { regex = "^storeSearch::.*", dst = "client/store", override = false },
    { regex = "^SFAT::.*", dst = "external/sfat", override = false },
    { regex = "^ClientBlobCache::.*", dst = "server/blob_cache", override = false },
    { regex = "^Molang.*", dst = "util/molang", override = false },
    { regex = "^TextureSetHelpers::.*", dst = "util", override = false },
    { regex = "^ValueProviders::.*", dst = "util", override = false },
    { regex = "^RideableComponentHelpers::.*", dst = "entity/components", override = false },
    { regex = "^RepairableItem.*Versioning.*", dst = "world/item/components/repairable", override = false },
    { regex = "^DurabilityItem.*Versioning.*", dst = "world/item/components/durability", override = false },
    { regex = "^ArmorItem.*Versioning.*", dst = "world/item/components/armor", override = false },
    { regex = "^WearableItem.*Versioning.*", dst = "world/item/components/wearable", override = false },
    { regex = ".*Item.*Versioning::.*", dst = "world/item/components", override = false },
    { regex = ".*OperationNode.*", dst = "world/level/newbiome", override = false },
    { regex = "^PositionTrackingDB::.*", dst = "world/level", override = false },
    { regex = "^FeatureLoading::.*", dst = "world/level/levelgen/feature", override = false },
    { regex = "^librarySearch::.*", dst = "common", override = false },
    { regex = "^Realms.*", dst = "client/network/realms", override = false },
    { regex = ".*_st$", dst = "external/openssl", override = false },
]
