package generate

import GENERATE_PATH
import namespaceMap
import java.io.File

object NamespaceGenerator {

    fun generate() {
        namespaceMap.forEach { (name, namespaceType) ->
            val file = File(GENERATE_PATH, namespaceType.getPath())
            file.writeText(
                """
// This Header is auto generated by BDSLiteLoader Toolchain
#pragma once
#define AUTO_GENERATED
#include "${namespaceType.getGlobalRelativePath()}"
${namespaceType.getRelativeInclusions()}
#define BEFORE_EXTRA
${namespaceType.beforeAddition}
#undef BEFORE_EXTRA

namespace $name {

#define AFTER_EXTRA
${namespaceType.afterAddition}
#undef AFTER_EXTRA
${namespaceType.genPublic()}
};
""".trimIndent()
            )
        }
    }
}